name: "QA"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
# https://github.com/marketplace/actions/checkout        
    - name: Checkout
      uses: actions/checkout@v5

    - name: Prepare
      run: |
        echo "//npm.pkg.github.com/:_authToken=${NPMRC}" >> .npmrc
        curl http://ipinfo.io

# https://github.com/marketplace/actions/docker-setup-qemu
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

# https://github.com/marketplace/actions/docker-setup-buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: v0.11.6

# https://github.com/marketplace/actions/alibaba-cloud-container-registry-acr-login        
    - name: Login ACR 
      uses: aliyun/acr-login@v1
      with:
        region-id: "${{ vars.ALICLOUD_REGION_ID}}" # example: cn-hangzhou
        access-key-id: "${{ secrets.ALICLOUD_ACCESS_KEY }}"
        access-key-secret: "${{ secrets.ALICLOUD_SECRET_KEY }}"

# https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64
        tags: registry.cn-shanghai.aliyuncs.com/macmini/chat_ops_payment_app:git-2-$(date +%s%3N)

