name: "QA"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        ref: stagging

    - name: Prepare
      run: |
        echo "//npm.pkg.github.com/:_authToken=${NPMRC}" >> .npmrc
        curl http://ipinfo.io

    - name: Generate timestamp
      id: timestamp
      run: echo "timestamp=$(date +%s%3N)" >> $GITHUB_OUTPUT

    - name: Get image name
      id: image_name
      run: |
        repo_name=${GITHUB_REPOSITORY##*/}
        image_name=${repo_name#wecom-clienteling-msv-}
        echo "IMAGE_NAME=${image_name}" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login ACR 
      uses: aliyun/acr-login@v1
      with:
        login-server: "https://${{ vars.ALICLOUD_REGISTRY }}"
        region-id: "${{ vars.ALICLOUD_REGION_ID }}"
        username: "${{ vars.ALICLOUD_REGISTRY_USERNAME }}"
        password: "${{ secrets.ALICLOUD_REGISTRY_PASSWORD }}"

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64
        tags: "${{ vars.ALICLOUD_REGISTRY }}/${{ vars.ALICLOUD_REGISTRY_QA_NAMESPACE }}/${{ steps.image_name.outputs.IMAGE_NAME }}:git-2-${{ steps.timestamp.outputs.timestamp }}"